M48
; DRILL file {KiCad 7.0.5} date Fri Sep 22 01:01:43 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-22T01:01:43+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X2.1539Y-1.7675
X2.3815Y-1.7675
T2
X2.6181Y-1.9657
X2.7362Y-1.9657
T0
M30
